# Generated by Django 5.0.6 on 2024-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Facts_Tracker_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('energy_value', models.SmallIntegerField()),
                ('proteins', models.SmallIntegerField()),
                ('total_fats', models.SmallIntegerField()),
                ('saturated_fats', models.SmallIntegerField()),
                ('carbohydrates', models.SmallIntegerField()),
                ('sugars', models.SmallIntegerField()),
                ('cholesterol', models.SmallIntegerField()),
                ('fiber', models.SmallIntegerField()),
                ('example', models.BooleanField(default=False)),
            ],
        ),
    ]
