# Generated by Django 5.0.6 on 2024-07-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Facts_Tracker_App', '0002_nutritionfacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionfacts',
            name='is_verified',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='carbohydrates',
            field=models.SmallIntegerField(verbose_name='Węglowodany:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='cholesterol',
            field=models.SmallIntegerField(verbose_name='Cholesterol:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='energy_value',
            field=models.SmallIntegerField(verbose_name='Wartość energetyczna:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='example',
            field=models.BooleanField(default=False, verbose_name='Pozycja dla tabeli wzorcowej'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='fiber',
            field=models.SmallIntegerField(verbose_name='Błonnik:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='product_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa produktu:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='proteins',
            field=models.SmallIntegerField(verbose_name='Białko:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='saturated_fats',
            field=models.SmallIntegerField(verbose_name='W tym tłuszcze nasycone:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sugars',
            field=models.SmallIntegerField(verbose_name='Cukry:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_fats',
            field=models.SmallIntegerField(verbose_name='Tłuszcze:'),
        ),
    ]
