# Generated by Django 5.0.6 on 2024-07-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Facts_Tracker_App', '0003_nutritionfacts_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionfacts',
            name='is_verified',
        ),
    ]
