# Generated by Django 5.0.6 on 2024-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Facts_Tracker_App', '0004_remove_nutritionfacts_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionfacts',
            name='carbohydrates',
            field=models.SmallIntegerField(blank=True, verbose_name='Węglowodany:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='cholesterol',
            field=models.SmallIntegerField(blank=True, verbose_name='Cholesterol:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='energy_value',
            field=models.SmallIntegerField(blank=True, verbose_name='Wartość energetyczna:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='fiber',
            field=models.SmallIntegerField(blank=True, verbose_name='Błonnik:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='proteins',
            field=models.SmallIntegerField(blank=True, verbose_name='Białko:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='saturated_fats',
            field=models.SmallIntegerField(blank=True, verbose_name='W tym tłuszcze nasycone:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sugars',
            field=models.SmallIntegerField(blank=True, verbose_name='W tym cukry:'),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_fats',
            field=models.SmallIntegerField(blank=True, verbose_name='Tłuszcze:'),
        ),
    ]
