# Generated by Django 5.0.6 on 2024-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Facts_Tracker_App', '0005_alter_nutritionfacts_carbohydrates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa treningu:')),
                ('level_of_experience', models.CharField(max_length=100, verbose_name='Stopień zaawansowania:')),
                ('intensity', models.CharField(max_length=100, verbose_name='Intensywność:')),
                ('kcal_burnt', models.SmallIntegerField(blank=True, verbose_name='Spalone kalorie:')),
                ('trained_part', models.SmallIntegerField(verbose_name='Trenowana partia mięśni:')),
                ('exercise_1', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 1:')),
                ('exercise_1_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_1_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_2', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 2:')),
                ('exercise_2_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_2_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_3', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 3:')),
                ('exercise_3_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_3_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_4', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 4:')),
                ('exercise_4_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_4_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_5', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 5:')),
                ('exercise_5_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_5_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('training_description', models.TextField(blank=True, verbose_name='Opis treningu:')),
            ],
        ),
    ]
