# Generated by Django 5.0.6 on 2024-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Facts_Tracker_App', '0006_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='trained_part',
            field=models.CharField(verbose_name='Trenowana partia mięśni:'),
        ),
    ]
