# Generated by Django 5.0.6 on 2024-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Facts_Tracker_App', '0008_alter_training_training_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwa treningu:'),
        ),
    ]
