# Generated by Django 5.0.6 on 2024-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutrition_Facts_Tracker_App', '0009_alter_training_training_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_description',
        ),
        migrations.AddField(
            model_name='training',
            name='exercise_1_description',
            field=models.TextField(blank=True, verbose_name='Opis ćwiczenia 1:'),
        ),
        migrations.AddField(
            model_name='training',
            name='exercise_2_description',
            field=models.TextField(blank=True, verbose_name='Opis ćwiczenia 2:'),
        ),
        migrations.AddField(
            model_name='training',
            name='exercise_3_description',
            field=models.TextField(blank=True, verbose_name='Opis ćwiczenia 3:'),
        ),
        migrations.AddField(
            model_name='training',
            name='exercise_4_description',
            field=models.TextField(blank=True, verbose_name='Opis ćwiczenia 4:'),
        ),
        migrations.AddField(
            model_name='training',
            name='exercise_5_description',
            field=models.TextField(blank=True, verbose_name='Opis ćwiczenia 5:'),
        ),
    ]
